In [2]:
from models.model import *


nz = 100
ngf = 64
nc = 3
ndf = 64
batch_size = 64
epochs = 1000
lrG = 0.0002
lrD = 0.0002
beta1 = 0.5
beta2 = 0.999
image_size = 128
data_root = "data/face"
output_dir = "output"
dataset = "face"
model_name = "DCGAN"

In [3]:
from torchsummary import summary

In [20]:
netG = Generator(nz, ngf, nc)

print(netG)

Generator(
  (main): Sequential(
    (0): ConvTranspose2d(100, 512, kernel_size=(4, 4), stride=(1, 1), bias=False)
    (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): ConvTranspose2d(512, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): ConvTranspose2d(256, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (7): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (8): ReLU(inplace=True)
    (9): ConvTranspose2d(128, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (10): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): ReLU(inplace=True)
    (12): ConvTranspose2d(64, 32, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (13): BatchNorm2d(

In [24]:
summary(netG, input_size=(100, 1, 1), device="cpu")

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
   ConvTranspose2d-1            [-1, 512, 4, 4]         819,200
       BatchNorm2d-2            [-1, 512, 4, 4]           1,024
              ReLU-3            [-1, 512, 4, 4]               0
   ConvTranspose2d-4            [-1, 256, 8, 8]       2,097,152
       BatchNorm2d-5            [-1, 256, 8, 8]             512
              ReLU-6            [-1, 256, 8, 8]               0
   ConvTranspose2d-7          [-1, 128, 16, 16]         524,288
       BatchNorm2d-8          [-1, 128, 16, 16]             256
              ReLU-9          [-1, 128, 16, 16]               0
  ConvTranspose2d-10           [-1, 64, 32, 32]         131,072
      BatchNorm2d-11           [-1, 64, 32, 32]             128
             ReLU-12           [-1, 64, 32, 32]               0
  ConvTranspose2d-13           [-1, 32, 64, 64]          32,768
      BatchNorm2d-14           [-1, 32,

In [25]:
netD = Discriminator(nc, ndf)

print(netD)

Discriminator(
  (main): Sequential(
    (0): Conv2d(3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (1): LeakyReLU(negative_slope=0.2, inplace=True)
    (2): Conv2d(64, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (3): LeakyReLU(negative_slope=0.2, inplace=True)
    (4): Conv2d(64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): LeakyReLU(negative_slope=0.2, inplace=True)
    (7): Conv2d(128, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (8): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): LeakyReLU(negative_slope=0.2, inplace=True)
    (10): Conv2d(256, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (11): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): LeakyReLU(negative_slope=0.2, 

In [30]:
summary(netD, input_size=(3, 128, 128), device="cpu")

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 64, 64]           3,072
         LeakyReLU-2           [-1, 64, 64, 64]               0
            Conv2d-3           [-1, 64, 32, 32]          65,536
         LeakyReLU-4           [-1, 64, 32, 32]               0
            Conv2d-5          [-1, 128, 16, 16]         131,072
       BatchNorm2d-6          [-1, 128, 16, 16]             256
         LeakyReLU-7          [-1, 128, 16, 16]               0
            Conv2d-8            [-1, 256, 8, 8]         524,288
       BatchNorm2d-9            [-1, 256, 8, 8]             512
        LeakyReLU-10            [-1, 256, 8, 8]               0
           Conv2d-11            [-1, 512, 4, 4]       2,097,152
      BatchNorm2d-12            [-1, 512, 4, 4]           1,024
        LeakyReLU-13            [-1, 512, 4, 4]               0
           Conv2d-14              [-1, 

In [ ]:
gan = DCGAN(nz, ngf, ndf, nc, batch_size, epochs, lrG, lrD, beta1, beta2, \
    image_size, data_root, output_dir, dataset, model_name, gpu_mode=True)

gan.train()

In [1]:
import numpy as np


In [10]:
a = np.array([1])
a.shape

(1,)

In [7]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [31]:
def lstm_cell_forward(xt, a_prev, c_prev, parameters):
    """
    Implement a single forward step of the LSTM-cell as described in Figure (4)

    Arguments:
    xt -- your input data at timestep "t", numpy array of shape (n_x, m).
    a_prev -- Hidden state at timestep "t-1", numpy array of shape (n_a, m)
    c_prev -- Memory state at timestep "t-1", numpy array of shape (n_a, m)
    parameters -- python dictionary containing:
                        Wf -- Weight matrix of the forget gate, numpy array of shape (n_a, n_a + n_x)
                        bf -- Bias of the forget gate, numpy array of shape (n_a, 1)
                        Wi -- Weight matrix of the update gate, numpy array of shape (n_a, n_a + n_x)
                        bi -- Bias of the update gate, numpy array of shape (n_a, 1)
                        Wc -- Weight matrix of the first "tanh", numpy array of shape (n_a, n_a + n_x)
                        bc --  Bias of the first "tanh", numpy array of shape (n_a, 1)
                        Wo -- Weight matrix of the output gate, numpy array of shape (n_a, n_a + n_x)
                        bo --  Bias of the output gate, numpy array of shape (n_a, 1)
                        Wy -- Weight matrix relating the hidden-state to the output, numpy array of shape (n_y, n_a)
                        by -- Bias relating the hidden-state to the output, numpy array of shape (n_y, 1)
                        
    Returns:
    a_next -- next hidden state, of shape (n_a, m)
    c_next -- next memory state, of shape (n_a, m)
    yt_pred -- prediction at timestep "t", numpy array of shape (n_y, m)
    cache -- tuple of values needed for the backward pass, contains (a_next, c_next, a_prev, c_prev, xt, parameters)
    
    Note: ft/it/ot stand for the forget/update/output gates, cct stands for the candidate value (c tilde),
          c stands for the memory value
    """

    # Retrieve parameters from "parameters"
    Wf = parameters["Wf"]
    bf = parameters["bf"]
    Wi = parameters["Wi"]
    bi = parameters["bi"]
    Wc = parameters["Wc"]
    bc = parameters["bc"]
    Wo = parameters["Wo"]
    bo = parameters["bo"]
    Wy = parameters["Wy"]
    by = parameters["by"]
    
    # Retrieve dimensions from shapes of xt and Wy
    n_x, m = xt.shape
    n_y, n_a = Wy.shape

    ### START CODE HERE ###
    # Concatenate a_prev and xt (≈3 lines)
    concat = np.zeros((n_a + n_x, m))
    concat[: n_a, :] = a_prev
    concat[n_a :, :] = xt

    # Compute values for ft, it, cct, c_next, ot, a_next using the formulas given figure (4) (≈6 lines)
    ft = sigmoid(np.dot(Wf, concat) + bf)
    print(ft)
    it = sigmoid(np.dot(Wi, concat) + bi)
    print(it)
    cct = np.tanh(np.dot(Wc, concat) + bc)
    print(cct)
    c_next = ft * c_prev + it * cct 
    ot = sigmoid(np.dot(Wo, concat) + bo)
    a_next = ot * np.tanh(c_next)
    
    # Compute prediction of the LSTM cell (≈1 line)
    yt_pred = np.dot(Wy, a_next) + by
    ### END CODE HERE ###

    # store values needed for backward propagation in cache
    cache = (a_next, c_next, a_prev, c_prev, ft, it, cct, ot, xt, parameters)

    return a_next, c_next, yt_pred, cache, ft, it, cct

In [29]:
xt = np.array([[2]])
Wy = np.array([[1,-1],[1,0]])
a_prev = np.array([[0],[1]])

n_x, m = xt.shape
n_y, n_a = Wy.shape

### START CODE HERE ###
    # Concatenate a_prev and xt (≈3 lines)
concat = np.zeros((n_a + n_x, m))
print(concat.shape)
concat[: n_a, :] = a_prev
concat[n_a :, :] = xt
print(concat)


(3, 1)
[[0.]
 [1.]
 [2.]]


In [34]:
np.random.seed(1)
xt = np.array([[2]])
a_prev = np.array([[0],[1]])
c_prev = np.array([[1],[1]])
Wf = np.array([[1,0,1],[0,1,0]])
bf = np.array([[-3],[-1]])
Wi = np.array([[1,1,-2],[0,1,0]])
bi = np.array([[5],[-2]])
Wo = np.array([[0,0,1],[-2,1,0]])
bo = np.array([[-1],[3]])
Wc = np.array([[1,0,1],[0,1,0]])
bc = np.array([[-3],[-1]])
Wy = np.array([[1,-1],[1,0]])
by = np.array([[1],[2]])

parameters = {"Wf": Wf, "Wi": Wi, "Wo": Wo, "Wc": Wc, "Wy": Wy, "bf": bf, "bi": bi, "bo": bo, "bc": bc, "by": by}

a_next, c_next, yt, cache, ft, it, cct = lstm_cell_forward(xt, a_prev, c_prev, parameters)
print("a_next = ", a_next)
print("a_next.shape = ", c_next.shape)
print("c_next = ", c_next)
print("c_next.shape = ", c_next.shape)
print("yt =", yt)
print("yt.shape = ", yt.shape)
print("cache =", cache)
print("len(cache) = ", len(cache))
print("*"*20)
print("ft = ", ft)
print(ft.shape)
print("it = ", it)
print(it.shape)
print("cct = ", cct)
print(cct.shape)


[[0.26894142]
 [0.5       ]]
[[0.88079708]
 [0.26894142]]
[[-0.76159416]
 [ 0.        ]]
a_next =  [[-0.2789329 ]
 [ 0.45380542]]
a_next.shape =  (2, 1)
c_next =  [[-0.40186849]
 [ 0.5       ]]
c_next.shape =  (2, 1)
yt = [[0.26726168]
 [1.7210671 ]]
yt.shape =  (2, 1)
cache = (array([[-0.2789329 ],
       [ 0.45380542]]), array([[-0.40186849],
       [ 0.5       ]]), array([[0],
       [1]]), array([[1],
       [1]]), array([[0.26894142],
       [0.5       ]]), array([[0.88079708],
       [0.26894142]]), array([[-0.76159416],
       [ 0.        ]]), array([[0.73105858],
       [0.98201379]]), array([[2]]), {'Wf': array([[1, 0, 1],
       [0, 1, 0]]), 'Wi': array([[ 1,  1, -2],
       [ 0,  1,  0]]), 'Wo': array([[ 0,  0,  1],
       [-2,  1,  0]]), 'Wc': array([[1, 0, 1],
       [0, 1, 0]]), 'Wy': array([[ 1, -1],
       [ 1,  0]]), 'bf': array([[-3],
       [-1]]), 'bi': array([[ 5],
       [-2]]), 'bo': array([[-1],
       [ 3]]), 'bc': array([[-3],
       [-1]]), 'by': array([[1],


In [36]:
print(ft*c_prev+it*cct)

[[-0.40186849]
 [ 0.5       ]]


In [37]:
ot = sigmoid(np.dot(Wo, concat) + bo)


[[0.73105858]
 [0.98201379]]


In [38]:
print(np.tanh(c_next))

[[-0.38154658]
 [ 0.46211716]]
